// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

package ccg_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//玩家信息
type PlayerData struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Nick                 *string  `protobuf:"bytes,2,req,name=nick" json:"nick,omitempty"`
	Headurl              *string  `protobuf:"bytes,3,req,name=headurl" json:"headurl,omitempty"`
	Status               *int32   `protobuf:"varint,4,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{0}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PlayerData) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *PlayerData) GetHeadurl() string {
	if m != nil && m.Headurl != nil {
		return *m.Headurl
	}
	return ""
}

func (m *PlayerData) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

//用户名登陆
type LoginNamepasswordReq struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Password             *string  `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	DeviceType           *int32   `protobuf:"varint,3,req,name=DeviceType" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginNamepasswordReq) Reset()         { *m = LoginNamepasswordReq{} }
func (m *LoginNamepasswordReq) String() string { return proto.CompactTextString(m) }
func (*LoginNamepasswordReq) ProtoMessage()    {}
func (*LoginNamepasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{1}
}

func (m *LoginNamepasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginNamepasswordReq.Unmarshal(m, b)
}
func (m *LoginNamepasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginNamepasswordReq.Marshal(b, m, deterministic)
}
func (m *LoginNamepasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginNamepasswordReq.Merge(m, src)
}
func (m *LoginNamepasswordReq) XXX_Size() int {
	return xxx_messageInfo_LoginNamepasswordReq.Size(m)
}
func (m *LoginNamepasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginNamepasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginNamepasswordReq proto.InternalMessageInfo

func (m *LoginNamepasswordReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LoginNamepasswordReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginNamepasswordReq) GetDeviceType() int32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

//设备登陆
type Login_DeviceReq struct {
	Udid                 *string  `protobuf:"bytes,1,req,name=udid" json:"udid,omitempty"`
	DeviceType           *int32   `protobuf:"varint,2,req,name=DeviceType" json:"DeviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_DeviceReq) Reset()         { *m = Login_DeviceReq{} }
func (m *Login_DeviceReq) String() string { return proto.CompactTextString(m) }
func (*Login_DeviceReq) ProtoMessage()    {}
func (*Login_DeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{2}
}

func (m *Login_DeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_DeviceReq.Unmarshal(m, b)
}
func (m *Login_DeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_DeviceReq.Marshal(b, m, deterministic)
}
func (m *Login_DeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_DeviceReq.Merge(m, src)
}
func (m *Login_DeviceReq) XXX_Size() int {
	return xxx_messageInfo_Login_DeviceReq.Size(m)
}
func (m *Login_DeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_DeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_Login_DeviceReq proto.InternalMessageInfo

func (m *Login_DeviceReq) GetUdid() string {
	if m != nil && m.Udid != nil {
		return *m.Udid
	}
	return ""
}

func (m *Login_DeviceReq) GetDeviceType() int32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

//微信QQ
type LoginWechatReq struct {
	Udid                 *string  `protobuf:"bytes,1,req,name=udid" json:"udid,omitempty"`
	DeviceType           *int32   `protobuf:"varint,2,req,name=DeviceType" json:"DeviceType,omitempty"`
	Headurl              *string  `protobuf:"bytes,3,req,name=headurl" json:"headurl,omitempty"`
	Type                 *int32   `protobuf:"varint,4,req,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginWechatReq) Reset()         { *m = LoginWechatReq{} }
func (m *LoginWechatReq) String() string { return proto.CompactTextString(m) }
func (*LoginWechatReq) ProtoMessage()    {}
func (*LoginWechatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{3}
}

func (m *LoginWechatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginWechatReq.Unmarshal(m, b)
}
func (m *LoginWechatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginWechatReq.Marshal(b, m, deterministic)
}
func (m *LoginWechatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginWechatReq.Merge(m, src)
}
func (m *LoginWechatReq) XXX_Size() int {
	return xxx_messageInfo_LoginWechatReq.Size(m)
}
func (m *LoginWechatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginWechatReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginWechatReq proto.InternalMessageInfo

func (m *LoginWechatReq) GetUdid() string {
	if m != nil && m.Udid != nil {
		return *m.Udid
	}
	return ""
}

func (m *LoginWechatReq) GetDeviceType() int32 {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return 0
}

func (m *LoginWechatReq) GetHeadurl() string {
	if m != nil && m.Headurl != nil {
		return *m.Headurl
	}
	return ""
}

func (m *LoginWechatReq) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

//登陆反馈
type Login_Respone struct {
	Type                 *int32   `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Nick                 *string  `protobuf:"bytes,2,req,name=nick" json:"nick,omitempty"`
	Id                   *int32   `protobuf:"varint,3,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_Respone) Reset()         { *m = Login_Respone{} }
func (m *Login_Respone) String() string { return proto.CompactTextString(m) }
func (*Login_Respone) ProtoMessage()    {}
func (*Login_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{4}
}

func (m *Login_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_Respone.Unmarshal(m, b)
}
func (m *Login_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_Respone.Marshal(b, m, deterministic)
}
func (m *Login_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_Respone.Merge(m, src)
}
func (m *Login_Respone) XXX_Size() int {
	return xxx_messageInfo_Login_Respone.Size(m)
}
func (m *Login_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Login_Respone proto.InternalMessageInfo

func (m *Login_Respone) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Login_Respone) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Login_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

//开房间
type RoomCreateReq struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Roomtype             *int32   `protobuf:"varint,2,req,name=roomtype" json:"roomtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreateReq) Reset()         { *m = RoomCreateReq{} }
func (m *RoomCreateReq) String() string { return proto.CompactTextString(m) }
func (*RoomCreateReq) ProtoMessage()    {}
func (*RoomCreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{5}
}

func (m *RoomCreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateReq.Unmarshal(m, b)
}
func (m *RoomCreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateReq.Marshal(b, m, deterministic)
}
func (m *RoomCreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateReq.Merge(m, src)
}
func (m *RoomCreateReq) XXX_Size() int {
	return xxx_messageInfo_RoomCreateReq.Size(m)
}
func (m *RoomCreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateReq proto.InternalMessageInfo

func (m *RoomCreateReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RoomCreateReq) GetRoomtype() int32 {
	if m != nil && m.Roomtype != nil {
		return *m.Roomtype
	}
	return 0
}

//开房间反馈
type RoomCreateRespone struct {
	Errorcode            *int32   `protobuf:"varint,1,req,name=errorcode" json:"errorcode,omitempty"`
	Roomid               *int32   `protobuf:"varint,2,req,name=roomid" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomCreateRespone) Reset()         { *m = RoomCreateRespone{} }
func (m *RoomCreateRespone) String() string { return proto.CompactTextString(m) }
func (*RoomCreateRespone) ProtoMessage()    {}
func (*RoomCreateRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{6}
}

func (m *RoomCreateRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomCreateRespone.Unmarshal(m, b)
}
func (m *RoomCreateRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomCreateRespone.Marshal(b, m, deterministic)
}
func (m *RoomCreateRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomCreateRespone.Merge(m, src)
}
func (m *RoomCreateRespone) XXX_Size() int {
	return xxx_messageInfo_RoomCreateRespone.Size(m)
}
func (m *RoomCreateRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomCreateRespone.DiscardUnknown(m)
}

var xxx_messageInfo_RoomCreateRespone proto.InternalMessageInfo

func (m *RoomCreateRespone) GetErrorcode() int32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

func (m *RoomCreateRespone) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

//开房间
type RoomJoinReq struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Roomid               *int32   `protobuf:"varint,2,req,name=roomid" json:"roomid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomJoinReq) Reset()         { *m = RoomJoinReq{} }
func (m *RoomJoinReq) String() string { return proto.CompactTextString(m) }
func (*RoomJoinReq) ProtoMessage()    {}
func (*RoomJoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{7}
}

func (m *RoomJoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomJoinReq.Unmarshal(m, b)
}
func (m *RoomJoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomJoinReq.Marshal(b, m, deterministic)
}
func (m *RoomJoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomJoinReq.Merge(m, src)
}
func (m *RoomJoinReq) XXX_Size() int {
	return xxx_messageInfo_RoomJoinReq.Size(m)
}
func (m *RoomJoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomJoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomJoinReq proto.InternalMessageInfo

func (m *RoomJoinReq) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RoomJoinReq) GetRoomid() int32 {
	if m != nil && m.Roomid != nil {
		return *m.Roomid
	}
	return 0
}

//开房间反馈
type RoomJoinRespone struct {
	Errorcode            *int32        `protobuf:"varint,1,req,name=errorcode" json:"errorcode,omitempty"`
	Pd                   []*PlayerData `protobuf:"bytes,2,rep,name=pd" json:"pd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomJoinRespone) Reset()         { *m = RoomJoinRespone{} }
func (m *RoomJoinRespone) String() string { return proto.CompactTextString(m) }
func (*RoomJoinRespone) ProtoMessage()    {}
func (*RoomJoinRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{8}
}

func (m *RoomJoinRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomJoinRespone.Unmarshal(m, b)
}
func (m *RoomJoinRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomJoinRespone.Marshal(b, m, deterministic)
}
func (m *RoomJoinRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomJoinRespone.Merge(m, src)
}
func (m *RoomJoinRespone) XXX_Size() int {
	return xxx_messageInfo_RoomJoinRespone.Size(m)
}
func (m *RoomJoinRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomJoinRespone.DiscardUnknown(m)
}

var xxx_messageInfo_RoomJoinRespone proto.InternalMessageInfo

func (m *RoomJoinRespone) GetErrorcode() int32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

func (m *RoomJoinRespone) GetPd() []*PlayerData {
	if m != nil {
		return m.Pd
	}
	return nil
}

//玩家准备
type RoomPlayerReady struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPlayerReady) Reset()         { *m = RoomPlayerReady{} }
func (m *RoomPlayerReady) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerReady) ProtoMessage()    {}
func (*RoomPlayerReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{9}
}

func (m *RoomPlayerReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerReady.Unmarshal(m, b)
}
func (m *RoomPlayerReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerReady.Marshal(b, m, deterministic)
}
func (m *RoomPlayerReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerReady.Merge(m, src)
}
func (m *RoomPlayerReady) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerReady.Size(m)
}
func (m *RoomPlayerReady) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerReady.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerReady proto.InternalMessageInfo

func (m *RoomPlayerReady) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

//玩家准备反馈信息
type RoomPlayerReadyRespone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPlayerReadyRespone) Reset()         { *m = RoomPlayerReadyRespone{} }
func (m *RoomPlayerReadyRespone) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerReadyRespone) ProtoMessage()    {}
func (*RoomPlayerReadyRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{10}
}

func (m *RoomPlayerReadyRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerReadyRespone.Unmarshal(m, b)
}
func (m *RoomPlayerReadyRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerReadyRespone.Marshal(b, m, deterministic)
}
func (m *RoomPlayerReadyRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerReadyRespone.Merge(m, src)
}
func (m *RoomPlayerReadyRespone) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerReadyRespone.Size(m)
}
func (m *RoomPlayerReadyRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerReadyRespone.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerReadyRespone proto.InternalMessageInfo

func (m *RoomPlayerReadyRespone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

//服务器发牌
type RoomGamestartRespone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Pk                   []*Poker `protobuf:"bytes,2,rep,name=pk" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomGamestartRespone) Reset()         { *m = RoomGamestartRespone{} }
func (m *RoomGamestartRespone) String() string { return proto.CompactTextString(m) }
func (*RoomGamestartRespone) ProtoMessage()    {}
func (*RoomGamestartRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{11}
}

func (m *RoomGamestartRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomGamestartRespone.Unmarshal(m, b)
}
func (m *RoomGamestartRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomGamestartRespone.Marshal(b, m, deterministic)
}
func (m *RoomGamestartRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomGamestartRespone.Merge(m, src)
}
func (m *RoomGamestartRespone) XXX_Size() int {
	return xxx_messageInfo_RoomGamestartRespone.Size(m)
}
func (m *RoomGamestartRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomGamestartRespone.DiscardUnknown(m)
}

var xxx_messageInfo_RoomGamestartRespone proto.InternalMessageInfo

func (m *RoomGamestartRespone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RoomGamestartRespone) GetPk() []*Poker {
	if m != nil {
		return m.Pk
	}
	return nil
}

//牌
type Poker struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type                 *int32   `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poker) Reset()         { *m = Poker{} }
func (m *Poker) String() string { return proto.CompactTextString(m) }
func (*Poker) ProtoMessage()    {}
func (*Poker) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{12}
}

func (m *Poker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poker.Unmarshal(m, b)
}
func (m *Poker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poker.Marshal(b, m, deterministic)
}
func (m *Poker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poker.Merge(m, src)
}
func (m *Poker) XXX_Size() int {
	return xxx_messageInfo_Poker.Size(m)
}
func (m *Poker) XXX_DiscardUnknown() {
	xxx_messageInfo_Poker.DiscardUnknown(m)
}

var xxx_messageInfo_Poker proto.InternalMessageInfo

func (m *Poker) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Poker) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

//叫分
type Call struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{13}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Call) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

//叫分反馈信息
type Call_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	Nextcallid           *int32   `protobuf:"varint,3,req,name=nextcallid" json:"nextcallid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call_Respone) Reset()         { *m = Call_Respone{} }
func (m *Call_Respone) String() string { return proto.CompactTextString(m) }
func (*Call_Respone) ProtoMessage()    {}
func (*Call_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{14}
}

func (m *Call_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call_Respone.Unmarshal(m, b)
}
func (m *Call_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call_Respone.Marshal(b, m, deterministic)
}
func (m *Call_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call_Respone.Merge(m, src)
}
func (m *Call_Respone) XXX_Size() int {
	return xxx_messageInfo_Call_Respone.Size(m)
}
func (m *Call_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Call_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Call_Respone proto.InternalMessageInfo

func (m *Call_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Call_Respone) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *Call_Respone) GetNextcallid() int32 {
	if m != nil && m.Nextcallid != nil {
		return *m.Nextcallid
	}
	return 0
}

//开始
type CallBegin_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallBegin_Respone) Reset()         { *m = CallBegin_Respone{} }
func (m *CallBegin_Respone) String() string { return proto.CompactTextString(m) }
func (*CallBegin_Respone) ProtoMessage()    {}
func (*CallBegin_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{15}
}

func (m *CallBegin_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallBegin_Respone.Unmarshal(m, b)
}
func (m *CallBegin_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallBegin_Respone.Marshal(b, m, deterministic)
}
func (m *CallBegin_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallBegin_Respone.Merge(m, src)
}
func (m *CallBegin_Respone) XXX_Size() int {
	return xxx_messageInfo_CallBegin_Respone.Size(m)
}
func (m *CallBegin_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_CallBegin_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_CallBegin_Respone proto.InternalMessageInfo

func (m *CallBegin_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *CallBegin_Respone) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

//出牌
type Pokerout struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Pk                   []*Poker `protobuf:"bytes,2,rep,name=pk" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pokerout) Reset()         { *m = Pokerout{} }
func (m *Pokerout) String() string { return proto.CompactTextString(m) }
func (*Pokerout) ProtoMessage()    {}
func (*Pokerout) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{16}
}

func (m *Pokerout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokerout.Unmarshal(m, b)
}
func (m *Pokerout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokerout.Marshal(b, m, deterministic)
}
func (m *Pokerout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokerout.Merge(m, src)
}
func (m *Pokerout) XXX_Size() int {
	return xxx_messageInfo_Pokerout.Size(m)
}
func (m *Pokerout) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokerout.DiscardUnknown(m)
}

var xxx_messageInfo_Pokerout proto.InternalMessageInfo

func (m *Pokerout) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Pokerout) GetPk() []*Poker {
	if m != nil {
		return m.Pk
	}
	return nil
}

//出牌反馈信息
type Pokerout_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Pk                   []*Poker `protobuf:"bytes,2,rep,name=pk" json:"pk,omitempty"`
	Nextid               *int32   `protobuf:"varint,3,req,name=nextid" json:"nextid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pokerout_Respone) Reset()         { *m = Pokerout_Respone{} }
func (m *Pokerout_Respone) String() string { return proto.CompactTextString(m) }
func (*Pokerout_Respone) ProtoMessage()    {}
func (*Pokerout_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{17}
}

func (m *Pokerout_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokerout_Respone.Unmarshal(m, b)
}
func (m *Pokerout_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokerout_Respone.Marshal(b, m, deterministic)
}
func (m *Pokerout_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokerout_Respone.Merge(m, src)
}
func (m *Pokerout_Respone) XXX_Size() int {
	return xxx_messageInfo_Pokerout_Respone.Size(m)
}
func (m *Pokerout_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokerout_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Pokerout_Respone proto.InternalMessageInfo

func (m *Pokerout_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Pokerout_Respone) GetPk() []*Poker {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *Pokerout_Respone) GetNextid() int32 {
	if m != nil && m.Nextid != nil {
		return *m.Nextid
	}
	return 0
}

//结算
type Gameend_Respone struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gameend_Respone) Reset()         { *m = Gameend_Respone{} }
func (m *Gameend_Respone) String() string { return proto.CompactTextString(m) }
func (*Gameend_Respone) ProtoMessage()    {}
func (*Gameend_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{18}
}

func (m *Gameend_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gameend_Respone.Unmarshal(m, b)
}
func (m *Gameend_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gameend_Respone.Marshal(b, m, deterministic)
}
func (m *Gameend_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gameend_Respone.Merge(m, src)
}
func (m *Gameend_Respone) XXX_Size() int {
	return xxx_messageInfo_Gameend_Respone.Size(m)
}
func (m *Gameend_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Gameend_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Gameend_Respone proto.InternalMessageInfo

//聊天
type Chattext struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Textid               *int32   `protobuf:"varint,2,req,name=textid" json:"textid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chattext) Reset()         { *m = Chattext{} }
func (m *Chattext) String() string { return proto.CompactTextString(m) }
func (*Chattext) ProtoMessage()    {}
func (*Chattext) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{19}
}

func (m *Chattext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chattext.Unmarshal(m, b)
}
func (m *Chattext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chattext.Marshal(b, m, deterministic)
}
func (m *Chattext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chattext.Merge(m, src)
}
func (m *Chattext) XXX_Size() int {
	return xxx_messageInfo_Chattext.Size(m)
}
func (m *Chattext) XXX_DiscardUnknown() {
	xxx_messageInfo_Chattext.DiscardUnknown(m)
}

var xxx_messageInfo_Chattext proto.InternalMessageInfo

func (m *Chattext) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chattext) GetTextid() int32 {
	if m != nil && m.Textid != nil {
		return *m.Textid
	}
	return 0
}

//表情
type Chatemo struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Emoid                *int32   `protobuf:"varint,2,req,name=emoid" json:"emoid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chatemo) Reset()         { *m = Chatemo{} }
func (m *Chatemo) String() string { return proto.CompactTextString(m) }
func (*Chatemo) ProtoMessage()    {}
func (*Chatemo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{20}
}

func (m *Chatemo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chatemo.Unmarshal(m, b)
}
func (m *Chatemo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chatemo.Marshal(b, m, deterministic)
}
func (m *Chatemo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chatemo.Merge(m, src)
}
func (m *Chatemo) XXX_Size() int {
	return xxx_messageInfo_Chatemo.Size(m)
}
func (m *Chatemo) XXX_DiscardUnknown() {
	xxx_messageInfo_Chatemo.DiscardUnknown(m)
}

var xxx_messageInfo_Chatemo proto.InternalMessageInfo

func (m *Chatemo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chatemo) GetEmoid() int32 {
	if m != nil && m.Emoid != nil {
		return *m.Emoid
	}
	return 0
}

//文本聊天
type Chatstring struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str                  *string  `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chatstring) Reset()         { *m = Chatstring{} }
func (m *Chatstring) String() string { return proto.CompactTextString(m) }
func (*Chatstring) ProtoMessage()    {}
func (*Chatstring) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{21}
}

func (m *Chatstring) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chatstring.Unmarshal(m, b)
}
func (m *Chatstring) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chatstring.Marshal(b, m, deterministic)
}
func (m *Chatstring) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chatstring.Merge(m, src)
}
func (m *Chatstring) XXX_Size() int {
	return xxx_messageInfo_Chatstring.Size(m)
}
func (m *Chatstring) XXX_DiscardUnknown() {
	xxx_messageInfo_Chatstring.DiscardUnknown(m)
}

var xxx_messageInfo_Chatstring proto.InternalMessageInfo

func (m *Chatstring) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chatstring) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

//聊天
type Chattext_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Textid               *int32   `protobuf:"varint,2,req,name=textid" json:"textid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chattext_Respone) Reset()         { *m = Chattext_Respone{} }
func (m *Chattext_Respone) String() string { return proto.CompactTextString(m) }
func (*Chattext_Respone) ProtoMessage()    {}
func (*Chattext_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{22}
}

func (m *Chattext_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chattext_Respone.Unmarshal(m, b)
}
func (m *Chattext_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chattext_Respone.Marshal(b, m, deterministic)
}
func (m *Chattext_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chattext_Respone.Merge(m, src)
}
func (m *Chattext_Respone) XXX_Size() int {
	return xxx_messageInfo_Chattext_Respone.Size(m)
}
func (m *Chattext_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Chattext_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Chattext_Respone proto.InternalMessageInfo

func (m *Chattext_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chattext_Respone) GetTextid() int32 {
	if m != nil && m.Textid != nil {
		return *m.Textid
	}
	return 0
}

//表情
type Chatemo_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Emoid                *int32   `protobuf:"varint,2,req,name=emoid" json:"emoid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chatemo_Respone) Reset()         { *m = Chatemo_Respone{} }
func (m *Chatemo_Respone) String() string { return proto.CompactTextString(m) }
func (*Chatemo_Respone) ProtoMessage()    {}
func (*Chatemo_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{23}
}

func (m *Chatemo_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chatemo_Respone.Unmarshal(m, b)
}
func (m *Chatemo_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chatemo_Respone.Marshal(b, m, deterministic)
}
func (m *Chatemo_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chatemo_Respone.Merge(m, src)
}
func (m *Chatemo_Respone) XXX_Size() int {
	return xxx_messageInfo_Chatemo_Respone.Size(m)
}
func (m *Chatemo_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Chatemo_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Chatemo_Respone proto.InternalMessageInfo

func (m *Chatemo_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chatemo_Respone) GetEmoid() int32 {
	if m != nil && m.Emoid != nil {
		return *m.Emoid
	}
	return 0
}

//文本聊天
type Chatstring_Respone struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str                  *string  `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chatstring_Respone) Reset()         { *m = Chatstring_Respone{} }
func (m *Chatstring_Respone) String() string { return proto.CompactTextString(m) }
func (*Chatstring_Respone) ProtoMessage()    {}
func (*Chatstring_Respone) Descriptor() ([]byte, []int) {
	return fileDescriptor_1eb1a68c9dd6d429, []int{24}
}

func (m *Chatstring_Respone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chatstring_Respone.Unmarshal(m, b)
}
func (m *Chatstring_Respone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chatstring_Respone.Marshal(b, m, deterministic)
}
func (m *Chatstring_Respone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chatstring_Respone.Merge(m, src)
}
func (m *Chatstring_Respone) XXX_Size() int {
	return xxx_messageInfo_Chatstring_Respone.Size(m)
}
func (m *Chatstring_Respone) XXX_DiscardUnknown() {
	xxx_messageInfo_Chatstring_Respone.DiscardUnknown(m)
}

var xxx_messageInfo_Chatstring_Respone proto.InternalMessageInfo

func (m *Chatstring_Respone) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Chatstring_Respone) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayerData)(nil), "ccg_pb.PlayerData")
	proto.RegisterType((*LoginNamepasswordReq)(nil), "ccg_pb.login_namepasswordReq")
	proto.RegisterType((*Login_DeviceReq)(nil), "ccg_pb.login_DeviceReq")
	proto.RegisterType((*LoginWechatReq)(nil), "ccg_pb.login_wechatReq")
	proto.RegisterType((*Login_Respone)(nil), "ccg_pb.login_Respone")
	proto.RegisterType((*RoomCreateReq)(nil), "ccg_pb.room_createReq")
	proto.RegisterType((*RoomCreateRespone)(nil), "ccg_pb.room_createRespone")
	proto.RegisterType((*RoomJoinReq)(nil), "ccg_pb.room_joinReq")
	proto.RegisterType((*RoomJoinRespone)(nil), "ccg_pb.room_joinRespone")
	proto.RegisterType((*RoomPlayerReady)(nil), "ccg_pb.room_playerReady")
	proto.RegisterType((*RoomPlayerReadyRespone)(nil), "ccg_pb.room_playerReadyRespone")
	proto.RegisterType((*RoomGamestartRespone)(nil), "ccg_pb.room_gamestartRespone")
	proto.RegisterType((*Poker)(nil), "ccg_pb.poker")
	proto.RegisterType((*Call)(nil), "ccg_pb.call")
	proto.RegisterType((*Call_Respone)(nil), "ccg_pb.call_Respone")
	proto.RegisterType((*CallBegin_Respone)(nil), "ccg_pb.call_begin_Respone")
	proto.RegisterType((*Pokerout)(nil), "ccg_pb.pokerout")
	proto.RegisterType((*Pokerout_Respone)(nil), "ccg_pb.pokerout_Respone")
	proto.RegisterType((*Gameend_Respone)(nil), "ccg_pb.gameend_Respone")
	proto.RegisterType((*Chattext)(nil), "ccg_pb.chattext")
	proto.RegisterType((*Chatemo)(nil), "ccg_pb.chatemo")
	proto.RegisterType((*Chatstring)(nil), "ccg_pb.chatstring")
	proto.RegisterType((*Chattext_Respone)(nil), "ccg_pb.chattext_Respone")
	proto.RegisterType((*Chatemo_Respone)(nil), "ccg_pb.chatemo_Respone")
	proto.RegisterType((*Chatstring_Respone)(nil), "ccg_pb.chatstring_Respone")
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor_1eb1a68c9dd6d429) }

var fileDescriptor_1eb1a68c9dd6d429 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0x37, 0x49, 0x9b, 0x0c, 0x6d, 0x93, 0x5a, 0x14, 0xa2, 0x0a, 0x50, 0xe5, 0x53, 0x10,
	0x52, 0x90, 0x7a, 0x28, 0x02, 0x71, 0x2c, 0x20, 0x71, 0xaa, 0x56, 0xbd, 0x70, 0x8a, 0x9c, 0xf5,
	0x28, 0x5d, 0x92, 0x5d, 0x1b, 0xdb, 0xa1, 0xcd, 0xbf, 0x47, 0xfe, 0xda, 0xa4, 0xc9, 0x6e, 0x81,
	0xde, 0x66, 0x46, 0xef, 0xbd, 0x79, 0x9e, 0x19, 0xc3, 0x09, 0xe3, 0x5c, 0xa1, 0xd6, 0x53, 0x21,
	0xe6, 0x63, 0xa9, 0x84, 0x11, 0x64, 0x3f, 0xcb, 0x66, 0x13, 0x39, 0xa5, 0x53, 0x80, 0xeb, 0x05,
	0x5b, 0xa1, 0xba, 0x62, 0x86, 0x91, 0x63, 0x48, 0x72, 0x3e, 0xdc, 0x3b, 0x4f, 0x46, 0x9d, 0x34,
	0xc9, 0x39, 0x21, 0xd0, 0x2e, 0xf3, 0x6c, 0x3e, 0x4c, 0xce, 0x93, 0x51, 0x2f, 0x75, 0x31, 0x19,
	0xc2, 0xc1, 0x2d, 0x32, 0xbe, 0x54, 0x8b, 0x61, 0xcb, 0x95, 0x63, 0x4a, 0x5e, 0xc0, 0xbe, 0x36,
	0xcc, 0x2c, 0xf5, 0xb0, 0xed, 0x14, 0x42, 0x46, 0x67, 0x70, 0xba, 0x10, 0xb3, 0xbc, 0x9c, 0x94,
	0xac, 0x40, 0xc9, 0xb4, 0xbe, 0x13, 0x8a, 0xa7, 0xf8, 0xcb, 0xc9, 0xb3, 0x02, 0x5d, 0x43, 0x2b,
	0xcf, 0x0a, 0x24, 0x67, 0xd0, 0x8d, 0x90, 0xd0, 0xb6, 0xca, 0xc9, 0x1b, 0x80, 0x2b, 0xfc, 0x9d,
	0x67, 0x78, 0xb3, 0x92, 0xe8, 0xba, 0x77, 0xd2, 0x8d, 0x0a, 0xfd, 0x02, 0x7d, 0xdf, 0xc8, 0xd7,
	0x42, 0x8b, 0x25, 0x0f, 0x6f, 0xea, 0xa5, 0x2e, 0xde, 0x92, 0x49, 0x76, 0x64, 0x74, 0x94, 0xb9,
	0xc3, 0xec, 0x96, 0x99, 0x27, 0xca, 0x3c, 0x32, 0x28, 0x02, 0x6d, 0x63, 0x39, 0x7e, 0x4c, 0x2e,
	0xa6, 0xdf, 0xe0, 0xc8, 0x37, 0x4d, 0x51, 0x4b, 0x51, 0x62, 0x05, 0xda, 0x5b, 0x83, 0x6a, 0xf7,
	0xe1, 0x77, 0xd6, 0x8a, 0x3b, 0xa3, 0x9f, 0xe1, 0x58, 0x09, 0x51, 0x4c, 0x32, 0x85, 0xcc, 0xb8,
	0x19, 0x6c, 0x6f, 0xf5, 0x0c, 0xba, 0x16, 0x61, 0xd6, 0xb6, 0xab, 0x9c, 0x7e, 0x07, 0xf2, 0x80,
	0xed, 0xbd, 0xbc, 0x82, 0x1e, 0x2a, 0x25, 0x54, 0x26, 0x78, 0x34, 0xb4, 0x2e, 0xd8, 0xbd, 0x5b,
	0x4e, 0xce, 0x83, 0x5a, 0xc8, 0xe8, 0x25, 0x1c, 0x3a, 0xad, 0x9f, 0x22, 0x2f, 0xeb, 0x7c, 0x34,
	0xf1, 0x6e, 0x60, 0xb0, 0xc1, 0xfb, 0x17, 0x07, 0x14, 0x12, 0x69, 0x55, 0x5a, 0xa3, 0x67, 0x17,
	0x64, 0xec, 0x4f, 0x7b, 0xbc, 0xbe, 0xeb, 0x34, 0x91, 0x9c, 0xd2, 0xa0, 0x2a, 0x5d, 0x39, 0x45,
	0xc6, 0x57, 0xdb, 0x8e, 0xe8, 0x5b, 0x78, 0xb9, 0x8d, 0x89, 0x06, 0xb6, 0xa1, 0x5f, 0xe1, 0xd4,
	0x41, 0x67, 0xac, 0x40, 0x6d, 0x98, 0x32, 0x0d, 0x40, 0xf2, 0x1a, 0x12, 0x39, 0x0f, 0xde, 0x8e,
	0xa2, 0x37, 0x29, 0xe6, 0xa8, 0xd2, 0x44, 0xce, 0xe9, 0x3b, 0xe8, 0xb8, 0xa4, 0xee, 0xef, 0x6d,
	0x6c, 0xc8, 0x1f, 0xc9, 0x08, 0xda, 0x19, 0x5b, 0x2c, 0x76, 0xb0, 0x03, 0x68, 0x95, 0xcb, 0x22,
	0x40, 0x6d, 0x48, 0xaf, 0xe1, 0xd0, 0x22, 0x27, 0x4d, 0xae, 0x76, 0x18, 0xf6, 0x9c, 0x4b, 0xbc,
	0x37, 0x96, 0x55, 0xdd, 0xd3, 0x46, 0x85, 0x5e, 0x02, 0x71, 0x8a, 0x53, 0xdc, 0xbc, 0xd2, 0xbf,
	0x3b, 0xf9, 0x08, 0x5d, 0xf7, 0x40, 0xb1, 0x34, 0xff, 0x3b, 0x9b, 0x1f, 0x30, 0x88, 0xd4, 0xc9,
	0xd3, 0xc6, 0x6b, 0x6f, 0xcc, 0xbe, 0xa1, 0x7a, 0x51, 0xc8, 0xe8, 0x09, 0xf4, 0xed, 0xe6, 0xb0,
	0xe4, 0x51, 0x99, 0x5e, 0x40, 0xd7, 0x7e, 0x77, 0x83, 0xf7, 0xa6, 0xee, 0x54, 0x8d, 0x97, 0x09,
	0xa7, 0xea, 0x33, 0xfa, 0x1e, 0x0e, 0x2c, 0x07, 0x0b, 0xb1, 0x43, 0x79, 0x0e, 0x1d, 0x2c, 0x44,
	0xc5, 0xf0, 0x09, 0x1d, 0x03, 0x58, 0x82, 0x36, 0x2a, 0x2f, 0x67, 0x75, 0xd3, 0xd3, 0x46, 0x85,
	0xef, 0x6d, 0x43, 0xfa, 0x09, 0x06, 0xd1, 0x54, 0xe3, 0x08, 0x9a, 0xcc, 0x7d, 0x80, 0x7e, 0x30,
	0xd7, 0x48, 0xad, 0x37, 0x69, 0x57, 0x5d, 0x99, 0x7c, 0x6c, 0xd5, 0x0f, 0xcd, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0x11, 0x0a, 0xc5, 0x68, 0x06, 0x00, 0x00,
}
